version: '3'

services:
  backend:
    build: .
    command: bash -c "python migrate.py && python run.py"
    depends_on:
      - database
    restart: on-failure
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@database:5432/test_db
      DEBUG: 1
    ports:
      - 8080:8000
  database:
      image: postgres:latest
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test_db
      volumes:
        - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
