name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    env:
      DATABASE_URL: postgresql+psycopg2://postgres:password@localhost:5432/test_db
      DEBUG: 1
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python migrate.py
      - name: Run tests
        run: pytest
