name: tests

on:
  push:
    branches:    
      - 'develop'
    paths-ignore:
      - 'README.md'
      - 'docker-compose*.yml'
      - 'Dockerfile'

jobs:
  test:
    env:
      DB_URL: postgresql+asyncpg://postgres:password@localhost:5432/test_db
      DEBUG: 0
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
